services:
  - type: worker
    name: amazon-price-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CHANNEL_ID
        sync: false
      - key: EMAIL_ADDRESS
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: SMTP_SERVER
        sync: false
      - key: SMTP_PORT
        sync: false
